### ISSUE TITLE
Feature requests for v0.0.1

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/leblad#5]
We would like to provide some features in our initial release, and as suggested in our [slack thread](https://dzcode.slack.com/archives/C011KGVKE15/p1600012480004200), we would like to have these features (sorted by votes).

- [x] `getWilayaList()` @Fcmam5 
- [x] `getAdjacentWilayas(number)` @Fcmam5 (#6 )
- [x] `getWilayaByCode(number)` @oussamabouchikhi (#8 )
- [x] `getWilayaByZipCode(number)` @abachi (#9 )
- [x] `getZipCodesForWilaya(number)` @anuragsati (#10 )
- [x] `getDairatsForWilaya(number)` @anuragsati (#11)

If you'd like to contribute:

- Comment on this issue with the feature you want to work on, and we will edit it to add your name, as in `getWilayaList()` example.
- Read our [contributing guidelines](https://github.com/dzcode-io/leblad/blob/develop/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/dzcode-io/leblad/blob/develop/.github/CODE_OF_CONDUCT.md).
- Add your feature (with tests of course 😄 ).
- Document it in the Readme (example: [`getWilayaList(projection)`](https://github.com/dzcode-io/leblad#getwilayalistprojection-string) )
- Submit a new pull request and point your branch to `develop`.

Please take your time, and if you need any help we will be very happy to help you. You can find us in [#repo-leblad](https://app.slack.com/client/T011KHDKCMC/C01A60X834N/thread/C01A60X834N-1600202165.000200) channel on our Slack.

**Comment by Fcmam5** [comment]
I will take `getAdjacentWilayas`

**Comment by abachi** [comment]
I will take `getWilayaByZipCode`

**Comment by anuragsati** [comment]
Hello ! can i take `getZipCodesForWilaya`

**Comment by Fcmam5** [comment]
> Hello ! can i take `getZipCodesForWilaya`

Please go ahead @anuragsati 😃 !

**Comment by anuragsati** [comment]
Hello @Fcmam5 can i take `getDairatsForWilaya` for Hacktoberfest?

**Comment by Fcmam5** [comment]
> Hello @Fcmam5 can i take `getDairatsForWilaya` for Hacktoberfest?

Hi @anuragsati, I would say we finish with v0.0.1 for now, and we'll create another issue with more features to add, for sure they will be for Hacktoberfest.

**Comment by anuragsati** [comment]
sure, so can i work on `getDairatsForWilaya` for now?

**Comment by Fcmam5** [comment]
Sure thing, please go ahead 😄 🙏 !

**Comment by Fcmam5** [comment]
@oussamabouchikhi, @abachi and @anuragsati Thank you very much for working on [v0.0.1](https://github.com/dzcode-io/leblad/releases/tag/v0.0.1) 🙏 .

**Comment by oussamabouchikhi** [comment]
> 
> 
> @oussamabouchikhi, @abachi and @anuragsati Thank you very much for working on [v0.0.1](https://github.com/dzcode-io/leblad/releases/tag/v0.0.1) 🙏 .

It was a pleasure working with you @Fcmam5 hope it's not the last time

**Comment by Fcmam5** [comment]
@anuragsati , as I promised we started creating issues for [hacktoberfest](https://github.com/dzcode-io/leblad/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest), welcome again 😄
